# Generated by Django 5.0.1 on 2024-01-22 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('created_on', models.DateField(default=datetime.datetime.today)),
                ('deadline', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'incomplete'), (1, 'complete')], default=0)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
